#Name: Khalid Alsuwaiyel 
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision "shell", path: "script.sh"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJIHTDXUBCEWFPSJQ"
    aws.secret_access_key = "6pOCLBnDiHUCTndQ6gTw9yscyLlJkxkoDqQNxAvh"
    aws.keypair_name = "alsuwaiyek1"
    aws.instance_type = "t2.micro"
    aws.security_groups = ["csc440-alsuwaiyek1"]
    aws.region = "us-west-2"
    aws.ami = "ami-8786c6b7"
    aws.tags = {'Name' => "alsuwaiyek1_HW7"}
    config.ssh.pty = true
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "/Users/khalidalsuwaiyel/Downloads/alsuwaiyek1.pem"
  end
end

